# Generated by Django 2.2.14 on 2020-07-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ffghhgfj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hytryuryu', models.BigIntegerField()),
            ],
        ),
    ]
